[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#14845f"
backgroundColor = "#f8fbff"
secondaryBackgroundColor = "#ffffff"
textColor = "#223044"
font = "sans serif"
